#
# ataraxia v1
#

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic
    - name: m165437
      url-base: https://github.com/M165437
    - name: efogdev #Other zmk-pmw3610-driver config option
      url-base: https://github.com/efogdev
    - name: nuovotaka
      url-base: https://github.com/nuovotaka
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
   # - name: bluedrink9
   #   url-base: https://github.com/bluedrink9
      
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards-ataraxia
      remote: miketronic
      revision: ataraxia_v1_dragscroll
    - name: zmk-pmw3610-driver-01
      remote: miketronic
      revision: test
   # - name: zmk-pmw3610-driver-02
   #   remote: miketronic
   #   revision: main
    - name: nice-view-gem
      remote: m165437
      revision: main
    - name: zmk-pointing-acceleration-alpha
      remote: nuovotaka
      revision: main
   # - name: zmk-poor-mans-led-indicator
   #   remote: bluedrink9
   #   revision: main
      
  self:
    path: config

