manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic
    - name: tubbytwins
      url-base: https://github.com/tubbytwins
    - name: glebsexy
      url-base: https://github.com/glebsexy
  projects:
    - name: zmk
      remote: miketronic
      revision: rp2040zero
   # - name: zmk
   #   remote: glebsexy
   #   revision: add-rp2040-zero
      import: app/west.yml
    - name: zmk-keyboards-10x2
      remote: miketronic
      revision: main
  self:
    path: config
