manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic
    - name: tubbytwins
      url-base: https://github.com/tubbytwins
  projects:
  #  - name: zmk
  #    remote: miketronic
  #    revision: rp2040zero
    - name: zmk
      remote: tubbytwins
      revision: rp2040-zero-plus-combos-fix
      import: app/west.yml
    - name: zmk-keyboards-10x2
      remote: miketronic
  self:
    path: config
