#
# ataraxia
#

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic
    - name: m165437
      url-base: https://github.com/M165437
    - name: efogdev
      url-base: https://github.com/efogdev
    - name: nuovotaka
      url-base: https://github.com/nuovotaka
    - name: n0rthPole
      url-base: https://github.com/n0rthPole
    - name: badjeff
      url-base: https://github.com/badjeff
      
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards-ataraxia
      remote: miketronic
      revision: main
   # - name: nice-view-gem
   #   remote: m165437
   #   revision: main
   # - name: zmk-pmw3610-driver
   #   remote: efogdev
   #   revision: main
   # - name: zmk-pointing-acceleration-alpha
   #   remote: nuovotaka
   #   revision: main
   # - name: zmk-pmw3610-driver
   #   remote: n0rthPole
   #   revision: main
   # - name: zmk-input-processor-report-rate-limit
   #   remote: badjeff
   #   revision: main
      
  self:
    path: config
