#
# ataraxia
#

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic
    - name: m165437
      url-base: https://github.com/M165437
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards-ataraxia
      remote: miketronic
      revision: main
    - name: nice-view-gem
      remote: m165437
      revision: main
  self:
    path: config
